### PR TITLE
Shaded protobuf

### PR DESCRIPTION
**Pull request by laugimethods**
To solve Incompatibility between java-nats-streaming & Spark: protobuf
versions conflict.:
https://github.com/nats-io/java-nats-streaming/issues/20

http://stackoverflow.com/questions/34487996/how-can-i-use-proto3-with-hadoop-spark

https://maven.apache.org/plugins/maven-shade-plugin/

### CODE REVIEW

**Comment by laugimethods** [comment]
That commit (build locally) does indeed solve the Spark Cluster issue!

**Comment by ColinSullivan1** [comment]
@laugimethods , Just following up - is this still an issue for you?

Thanks,
Colin

**Comment by laugimethods** [comment]
@ColinSullivan1, no more an issue for me (https://github.com/Logimethods/nats-connector-spark/commit/fa6d3e91c90db999e680376108b87ae8d67dbb41), but could still be one for other projects making use of both protobuf and NATS Streaming.

**Comment by ColinSullivan1** [comment]
@laugimethods , I agree, good contribution!  If you fix the conflict and tests continue to pass, I'll be happy to merge this.

**Comment by laugimethods** [comment]
@ColinSullivan1, I did add the `maven-compiler-plugin` & `maven-release-plugin` from the master branch...

**Comment by ColinSullivan1** [comment]
LGTM, Thank you @laugimethods for your contribution!

**Pull request merged**
