### PR TITLE
Serializable options.builder

### PR DESCRIPTION
**Pull request by laugimethods**
To be consistent with
https://github.com/nats-io/java-nats-streaming/pull/56

### CODE REVIEW

**Comment by laugimethods** [comment]
The Build is successful locally:
```
12:07 ~/Documents/GitHub/java-nats-streaming-fork > mvn generate-sources compile test
.../...
Tests run: 119, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:report (post-unit-test) @ java-nats-streaming ---
[INFO] Loading execution data file /Users/laugimethods/Documents/GitHub/java-nats-streaming-fork/target/coverage-reports/jacoco-ut.exec
[INFO] Analyzed bundle 'java-nats-streaming' with 12 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.524 s
[INFO] Finished at: 2017-05-18T12:07:56-04:00
[INFO] Final Memory: 35M/481M
[INFO] ------------------------------------------------------------------------
```
The Travis build needs to be restarted?

**Comment by ColinSullivan1** [comment]
@laugimethods , Thank you, I appreciate the PR here to keep the options consistent.  I'll keep on Travis until we get a good build, the errors are just flappers.

**Comment by ColinSullivan1** [comment]
@laugimethods , the failing test may be more than a flapper.  I'll take a look.

**Comment by laugimethods** [comment]
I think I got the root cause of the build failure:
```
Tests in error: 
  OptionsBuilderTest.setUpBeforeClass:41 » IO nats: no servers available for con...
```
Actually, I had to start manually a NATS Server (`gnatsd -p 4222&`), which is used to get a `Connection`:
```
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
    	natsConn = Nats.connect();
        testOptsBuilder = new Options.Builder()
        		.pubAckWait(Duration.ofMillis(500))
                .connectWait(Duration.ofMillis(1500))
                .discoverPrefix("PrEfiX")
                .maxPubAcksInFlight(10000)
                .natsConn(natsConn)
                .natsUrl("nats://nats");
    }
```
Therefore, we have to options:
* don't set the `natsConn(natsConn)` (that field is `transient`anyway)
* start the `gnatsd` server

**Comment by laugimethods** [comment]
(I might have a third option to solve the Build Issue)

**Comment by ColinSullivan1** [comment]
@laugimethods , I think removing `setupBeforeClass` and passing a null NATS conn would suffice (first option).

If you did want to test a non-nil NATS conn for perfection's sake (not-necessary IMO), I'd suggest removing `setupBeforeClass` and starting a NATS server as you mentioned in your second option.

...something like this:
```
    @Test
    public void testSerializable() throws ClassNotFoundException, IOException {
	try (NatsStreamingServer srv = runServer("test-cluster")) {
            Connection natsConn = new io.nats.client.ConnectionFactory().createConnection();
            Options.Builder testOptsBuilder = new Options.Builder()
					.pubAckWait(Duration.ofMillis(500))
					.connectWait(Duration.ofMillis(1500))
					.discoverPrefix("PrEfiX")
					.maxPubAcksInFlight(10000)
					.natsConn(natsConn)
					.natsUrl("nats://nats");
	    final Options.Builder serializedTestOpts = (Options.Builder) UnitTestUtilities.serializeDeserialize(testOptsBuilder);
            assertTrue(equals(testOptsBuilder, serializedTestOpts));
	}
    }
```

**Comment by laugimethods** [comment]
@ColinSullivan1 Well, the third option (which is included in the update of this PR and did pass all Travis builds and checks) does keep the test on a non-nil NATS conn (I agree not-necessary, but provides some safety in case of a removed `transient` flag) while not requiring a Nats Server to be running.
To do so, I created an empty NATS conn just for the purpose of this test.

**Comment by laugimethods** [comment]
@ColinSullivan1 BTW, The code you are using to start the NATS server in `testSerializable()` is indeed inspiring.

**Comment by ColinSullivan1** [comment]
@laugimethods , Would you mind giving the option of starting the server in the test method a try?  I'm aiming to reduce and simplify the code base (including tests) moving forward.

**Comment by laugimethods** [comment]
The build failed (but not locally).
Is it because of a sleep that is not long enough (for Travis)?
```
    private static NatsStreamingServer runServer(String clusterId, boolean debug) {
        NatsStreamingServer srv = new NatsStreamingServer(clusterId, debug);
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return srv;
    }
```

**Comment by laugimethods** [comment]
Couldn't we use `lsof -i:$port` through `java.lang.ProcessBuilder.ProcessBuilder(List<String> command)` to wait until the `nats-streaming-server`default port is indeed in use (meaning that the server is up and running)?

**Comment by ColinSullivan1** [comment]
Yeah, this needs to be fixed, sorry you are running into that.  In C#, to mitigate the slow CI, I continually tried creating NATS connections with a back off.  https://github.com/nats-io/csharp-nats-streaming/blob/master/STAN.Client.UnitTests/UnitTestUtilities.cs#L44  I can add this (probably mid next week), or if you have time, that fix would be a great addition.

**Comment by laugimethods** [comment]
"or if you have time, that fix would be a great addition" I'm on it!

**Comment by laugimethods** [comment]
Looks like the root cause of the build failure is not a timeout:
```
[TEST START] testSerializable
java.io.IOException: Cannot run program "/home/travis/build/nats-io/java-nats-streaming/target/nats-streaming-server" (in directory "target"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at io.nats.streaming.NatsStreamingServer.start(NatsStreamingServer.java:119)
```

**Comment by laugimethods** [comment]
```
NatsStreamingServer srv = runServer(UnitTestUtilities.testClusterName)) {
            Connection natsConn = new io.nats.client.ConnectionFactory().createConnection();
```
Isn't the natsConn expecting a NATS server instead of a NATS _Streaming_ server?

**Comment by laugimethods** [comment]
Shouldn't `runServer(String clusterId)` be replaced by `createServerOnPort(...)` since they look equivalent?

**Comment by ColinSullivan1** [comment]
@laugimethods , Good question - the NATS streaming server is architecturally a NATS client, working as a layer above NATS.  By default it conveniently has a NATS server embedded in it, but it can also run standalone and connect to a NATS server.

Since the streaming server in this test does have an embedded NATS server, we can connect to it as a standard NATS client as well as a streaming client.  The test could use `createServerOnPort`, or even `startDefaultServer`.  Ultimately, this test code needs to be refactored to incorporate the same delay logic, but that is a different PR.

**Comment by laugimethods** [comment]
Ok, I'll use `createServerOnPort`instead & see how the test will perform...

**Pull request merged**
